allow using enums on Router StaticSegment
leptos-rs/leptos pull request #2685
Opened 2024-07-13 02:41 UTC by mahmoud-eltahawy

i just wanted to suggest the idea of enums in router path

in way that leans into action

2024-07-15 15:36 UTC, mahmoud-eltahawy commented
the added example is a copy of router example but i changed routes to use enum instead

2024-07-16 14:45 UTC, gbj requested changes
Thanks! This looks good.

I would rather not include a separate example, as multiplying examples for specific features just increases the maintenance burden over time. Not sure if you have a good idea for documenting/publicizing this? Maybe a comment in the `router` example? Or it can be added to the future version of the book when it is updated for 0.7

2024-07-16 14:45 UTC, gbj commented on router/src/matching/horizontal/static_segment.rs
> +    fn into_str(&self) -> &'static str;
I'd recommend `as_path()` as a name for this method: `as_` in line with the [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv) for a lightweight `&`-to-`&` conversion, and `as_path()` to give a little more context than `as_str()`.

2024-07-16 14:45 UTC, gbj commented on router/src/matching/horizontal/static_segment.rs
> +pub trait Routable: Debug + Clone {
For single-method traits, it's best to name it the same as the trait itself -- So given my proposal of `as_path`, I'd suggest `AsPath` for the trait name.

The `Debug + Clone` trait bounds are not necessary -- as long as they are implemented on your enum they do not need to be bounds on the trait.

2024-07-18 22:19 UTC, gbj commented
Looks good, thanks!

2024-07-18 22:20 UTC, merged